/**
 * PageHeader 组件 — 样式常量
 */
export const PAGE_HEADER_STYLE = {
  CONTAINER_PADDING_HORIZONTAL: 16,
  CONTAINER_PADDING_TOP: 16,
  CONTAINER_PADDING_BOTTOM: 12,
  TITLE_FONT_SIZE: 18,
  TITLE_FONT_WEIGHT: "600" as const,
  TITLE_COLOR: "#FFFFFF",
  BACK_ICON_NAME: "chevron-back" as const,
  BACK_ICON_SIZE: 24,
  BACK_ICON_COLOR: "#FFFFFF",
  BACK_BTN_PADDING: 8,
  PLACEHOLDER_WIDTH: 40,
  HEADER_BG_COLOR: "#000",
} as const;
